/*
  # Add AI Generation Features

  1. Changes to Existing Tables
    - Add `generated_by_ai` column to `questions` table
      - Boolean flag to indicate if question was generated by AI
      - Defaults to false for existing and manually created questions

  2. New Tables
    - `ai_generation_logs`
      - `id` (uuid, primary key)
      - `user_id` (uuid, references users)
      - `evaluation_id` (uuid, nullable, references evaluations)
      - `content_source` (text) - 'manual_text' or 'file_upload'
      - `file_type` (text, nullable) - 'pdf', 'txt', etc.
      - `content_length` (integer) - length of content processed
      - `questions_requested` (integer) - number of questions requested
      - `questions_generated` (integer) - number of questions actually generated
      - `tokens_used` (integer, nullable) - OpenAI tokens consumed
      - `generation_time_ms` (integer) - time taken to generate
      - `success` (boolean) - whether generation succeeded
      - `error_message` (text, nullable) - error details if failed
      - `created_at` (timestamp)

  3. Security
    - Enable RLS on new table
    - Add policies for authenticated users to view their own logs
    - Add policies for admins to view all logs

  4. Important Notes
    - This migration is idempotent and safe to run multiple times
    - Existing questions will have generated_by_ai = false by default
    - Logs table helps track AI usage for auditing and cost monitoring
*/

-- Add generated_by_ai column to questions table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'questions' AND column_name = 'generated_by_ai'
  ) THEN
    ALTER TABLE questions ADD COLUMN generated_by_ai boolean DEFAULT false;
  END IF;
END $$;

-- Create ai_generation_logs table
CREATE TABLE IF NOT EXISTS ai_generation_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  evaluation_id uuid REFERENCES evaluations(id) ON DELETE SET NULL,
  content_source text NOT NULL CHECK (content_source IN ('manual_text', 'file_upload')),
  file_type text,
  content_length integer NOT NULL DEFAULT 0,
  questions_requested integer NOT NULL,
  questions_generated integer NOT NULL DEFAULT 0,
  tokens_used integer,
  generation_time_ms integer NOT NULL,
  success boolean DEFAULT false,
  error_message text,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on ai_generation_logs
ALTER TABLE ai_generation_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own logs
CREATE POLICY "Users can view own AI generation logs"
  ON ai_generation_logs
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Policy: Admins can view all logs (assuming admins have a role field)
CREATE POLICY "Admins can view all AI generation logs"
  ON ai_generation_logs
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  );

-- Policy: Authenticated users can insert their own logs
CREATE POLICY "Users can insert own AI generation logs"
  ON ai_generation_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Create index for faster queries on user_id and created_at
CREATE INDEX IF NOT EXISTS idx_ai_generation_logs_user_id ON ai_generation_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_generation_logs_created_at ON ai_generation_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_generation_logs_success ON ai_generation_logs(success);

-- Create index on questions.generated_by_ai for filtering
CREATE INDEX IF NOT EXISTS idx_questions_generated_by_ai ON questions(generated_by_ai);
